title: WoW Wiki Ita
description: World of Warcraft - wiki italiana
show_downloads: true
git_branch: master
logo_url: https://wowgame.github.io/wiki-en/assets/images/World-of-Warcraft-Logo.jpg
google_analytics:
theme: 
include: ["_pages", "_posts"]
wiki_folder: _pages
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:kayohas4w7e
comments: true
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
