title: Wiki Wotlk
description: World of Warcraft - Wrath of The Lich King wiki 
show_downloads: true
git_branch: master
logo_url: http://wowgame.github.io/wiki-wotlk-en/assets/images/WrathLogo.png
google_analytics:
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:kayohas4w7e
comments: true
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
